import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import {
  FaArrowLeft,
  FaFilePdf,
  FaCheckCircle,
  FaExclamationTriangle,
  FaTools,
  FaLightbulb,
  FaCalendarAlt,
} from "react-icons/fa";
import { CircularProgressbar, buildStyles } from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";

import API from "../services/api";
import Navbar from "../components/Navbar";

function ResumeDetails() {
  const { id } = useParams();

  const [resume, setResume] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchResume();
  }, []);

  const fetchResume = async () => {
    try {
      const res = await API.get(`/resume/${id}`);
      setResume(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-100 via-indigo-50 to-slate-100">
        {" "}
        <div className="w-16 h-16 border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin"></div>
        <h2 className="mt-6 text-2xl font-bold text-gray-800">
          Loading Resume Report...
        </h2>
        <p className="mt-2 text-gray-500">
          Please wait while we fetch your AI analysis.
        </p>
      </div>
    );
  }

  const score = resume.atsScore || 0;

  const scoreText =
    score >= 95
      ? "Outstanding"
      : score >= 90
        ? "Excellent"
        : score >= 80
          ? "Very Good"
          : score >= 70
            ? "Good"
            : score >= 60
              ? "Fair"
              : "Needs Improvement";

  const scoreColor =
    score >= 90
      ? "#16a34a"
      : score >= 80
        ? "#22c55e"
        : score >= 70
          ? "#f59e0b"
          : score >= 60
            ? "#f97316"
            : "#ef4444";

  return (
    <div className="min-h-screen bg-slate-100">
      <Navbar />

      <div className="max-w-7xl mx-auto p-10">
        <Link
          to="/dashboard"
          className="inline-flex items-center gap-2 rounded-xl px-4 py-2 bg-white border border-slate-200 shadow-sm text-indigo-600 font-semibold hover:shadow-md hover:bg-indigo-50 transition-all duration-300 mb-8"
        >
          <FaArrowLeft />
          Back to Dashboard
        </Link>

        {/* Header */}

        <div className="bg-white/80 backdrop-blur-md rounded-3xl border border-slate-200 shadow-sm p-8">
          <div className="grid lg:grid-cols-2 gap-10 items-center">
            {/* Left */}

            <div>
              <div className="flex items-center gap-4">
                <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-red-100 to-red-50 flex items-center justify-center shadow-sm">
                  <FaFilePdf className="text-red-600 text-4xl" />
                </div>

                <div>
                  <h1 className="text-4xl font-bold text-gray-800">
                    AI Analysis Report
                  </h1>

                  <p className="text-gray-500 mt-2">
                    {resume.originalName || "Resume.pdf"}
                  </p>
                  <p className="text-sm text-gray-400 mt-1">
                    Generated by AI Resume Reviewer
                  </p>

                  <div className="flex items-center gap-2 mt-3 text-gray-500">
                    <FaCalendarAlt />

                    {new Date(resume.createdAt).toLocaleDateString()}
                  </div>
                </div>
              </div>
            </div>

            {/* Right */}

            <div className="flex justify-center">
              <div className="w-64">
                <CircularProgressbar
                  value={score}
                  text={`${score}%`}
                  styles={buildStyles({
                    pathColor: scoreColor,
                    textColor: scoreColor,
                    trailColor: "#CBD5E1",
                    textSize: "18px",
                  })}
                />
                <div className="mt-4 flex justify-center">
                  <span
                    className={`px-4 py-2 rounded-full font-semibold text-sm ${
                      score >= 80
                        ? "bg-emerald-100 text-emerald-700"
                        : score >= 60
                          ? "bg-amber-100 text-amber-700"
                          : "bg-red-100 text-red-700"
                    }`}
                  >
                    {scoreText}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="grid md:grid-cols-3 gap-6 mt-8">
          <div
            className=" bg-white/80
backdrop-blur-md
border
border-slate-200
rounded-2xl
shadow-sm
hover:shadow-lg
hover:-translate-y-1
transition-all
duration-300 p-6 text-center"
          >
            <p className="text-gray-500">Strengths</p>

            <h2 className="text-5xl font-bold text-green-600 mt-2">
              {resume.strengths.length}
            </h2>
          </div>

          <div
            className="bg-white/80
backdrop-blur-md
border
border-slate-200
rounded-2xl
shadow-sm
hover:shadow-lg
hover:-translate-y-1
transition-all
duration-300 p-6 text-center"
          >
            <p className="text-gray-500">Missing Skills</p>

            <h2 className="text-4xl font-bold text-yellow-600 mt-2">
              {resume.missingSkills.length === 0
                ? "None"
                : resume.missingSkills.length}
            </h2>
          </div>

          <div
            className="bg-white/80
backdrop-blur-md
border
border-slate-200
rounded-2xl
shadow-sm
hover:shadow-lg
hover:-translate-y-1
transition-all
duration-300 p-6 text-center"
          >
            <p className="text-gray-500">Suggestions</p>

            <h2 className="text-4xl font-bold text-purple-600 mt-2">
              {resume.suggestions.length}
            </h2>
          </div>
        </div>
        {/* Summary */}
        <div className="bg-white rounded-3xl shadow-xl border border-slate-200 p-8 mt-8 hover:shadow-2xl transition duration-300">
          <h2 className="text-3xl font-bold mb-5">Professional Summary</h2>

          <p className="text-gray-700 leading-8">{resume.summary}</p>
        </div>

        {/* Cards */}

        <div className="grid md:grid-cols-2 gap-8 mt-8">
          {/* Strengths */}

          <div className="bg-white/80 backdrop-blur-md rounded-3xl border border-slate-200 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 p-8">
            <div className="flex items-center gap-3 mb-6">
              <FaCheckCircle className="text-emerald-600 text-3xl" />

              <h2 className="text-2xl font-bold text-emerald-700">Strengths</h2>
            </div>

            <ul className="space-y-3">
              {resume.strengths.map((item, index) => (
                <li key={index} className="flex items-start gap-3">
                  <span className="text-green-600">✔</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Weaknesses */}

          <div className="bg-white/80 backdrop-blur-md rounded-3xl border border-slate-200 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 p-8">
            <div className="flex items-center gap-3 mb-6">
              <FaExclamationTriangle className="text-red-500 text-3xl" />
              <h2 className="text-2xl font-bold text-red-600">Weaknesses</h2>
            </div>

            <ul className="space-y-3">
              {resume.weaknesses.map((item, index) => (
                <li key={index} className="flex items-start gap-3">
                  <span className="text-red-600">⚠</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Missing Skills */}

          {resume.missingSkills && resume.missingSkills.length > 0 ? (
            <div className="bg-white/80 backdrop-blur-md rounded-3xl border border-slate-200 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 p-8">
              <div className="flex items-center gap-3 mb-6">
                <FaTools className="text-amber-500 text-3xl" />

                <h2 className="text-2xl font-bold text-amber-600">
                  Missing Skills
                </h2>
              </div>

              <ul className="space-y-3">
                {resume.missingSkills.map((item, index) => (
                  <li key={index} className="flex items-start gap-3">
                    <span className="text-yellow-600">🛠</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </div>
          ) : (
            <div className="bg-white/80 backdrop-blur-md rounded-3xl border border-green-200 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 p-8">
              <div className="flex items-center gap-3 mb-4">
                <FaCheckCircle className="text-green-600 text-3xl" />

                <h2 className="text-2xl font-bold text-green-600">
                  Perfect Skill Match
                </h2>
              </div>

              <p className="text-gray-700 leading-7">
                Your resume covers the major skills required for this position.
                No significant skill gaps were detected.
              </p>
            </div>
          )}
          {/* Suggestions */}

          <div className="bg-white/80 backdrop-blur-md rounded-3xl border border-slate-200 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 p-8">
            <div className="flex items-center gap-3 mb-6">
              <FaLightbulb className="text-violet-600 text-3xl" />

              <h2 className="text-2xl font-bold text-violet-600">
                AI Suggestions
              </h2>
            </div>

            <ul className="space-y-3">
              {resume.suggestions.map((item, index) => (
                <li key={index} className="flex items-start gap-3">
                  <span className="text-purple-600">💡</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ResumeDetails;
